### ISSUE TITLE
need help to compile in vs2013

### ISSUE THREAD

**Issue by kohlhaas1808** [gilbo/cork#28]
Hi,

i need help to compile cork in vs2013.
In ubuntu i just use the make file to compile and it works like a charm.
But in windows with vs2013 i dont know how to get it to work.
is there a tutorial to do that?

**Comment by gilbo** [comment]
To be honest, I’m not much of a windows developer.

I added the windows stuff to help out someone who was initially looking at using the code.

— Gilbert
