### ISSUE TITLE
exception thrown on visual studio2017+windows10_x64 during computeing Difference with ballA\ballB

### ISSUE THREAD

**Issue by samyuchao** [gilbo/cork#40]
with win32, it is successful to do all commands.
with x64, building is successful, and run into computeDifference(...),  but exception thrown  during computeing Difference with ballA\ballB.
Is there any special setting on x64? 
![image](https://user-images.githubusercontent.com/10825626/39299566-9269f618-497b-11e8-998f-d99763dc7c60.png)

**Comment by danilopeixoto** [comment]
I solved this problem by replacing `unsigned long` type (declared in the `triangle.c` file to represent pointer data) with `unsigned __int64` type. The `unsigned long` is the size of 4 bytes and `unsigned __int64` is 8 bytes (https://msdn.microsoft.com/en-us/library/s3f49ktz.aspx). Try to use 8 bytes to store pointer data.
